name: Phoenix Test Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Debug directory
      run: |
        pwd
        ls -R     
        
    - name: Run Maven Tests
      run: mvn clean test -Dsurefire.suiteXmlFiles=testng.xml -Denv=qa
     




